#!/usr/bin/env bash
ROOT=${PWD}
update() {
    set -x
    cd $1
    git pull origin
    npm install
    node index.js
    cd ${ROOT}
    { set +x; } 2>/dev/null
}

for i in www to-meteor
do
    update $i
done
