---
title: "<code>test161</code>: The OS/161 Testing Tool"
spelling_exceptions:
  - PPA
  - YAML
  - GVM
---
:sectnums:

== Introduction

[.lead]
{test161} is the OS/161 testing tool designed and implemented by
https://blue.cse.buffalo.edu/people/shaseley/[Scott Haseley] and
https://blue.cse.buffalo.edu/people/ychen78/[Yihong Chen]. It allows you both
to test your assignments locally and submit them for remote evaluation.

Below we run through how to install, configure, run, and use {test161}. While
the specific testing target will change from assignment to assignment, we use
{asst1} below as an example. Note that this tutorial duplicates some
information from the `test161` {readme} located on the project's
https://github.com/ops-class/test161[GitHub page].

=== Installation

{test161} is distributed as part of the {toolchain}, which is packaged for
Ubuntu Linux 14.04 "Trusty". Install and upgrade it from the
https://www.ops-class.org/asst/toolchain/#ppa[`ops-class.org` PPA, role="noexternal"]:

[source,bash]
----
sudo add-apt-repository ppa:geoffrey-challen/os161-toolchain
sudo apt-get update
sudo apt-get install os161-toolchain
# sudo apt-get install test161 # If you don't want the entire toolchain
----

If you need an Ubuntu environment to develop OS/161, you
may want to try our
https://www.ops-class.org/asst/toolchain/#vagrant[`ops-class.org` Vagrant virtual machine, role="noexternal"].

If needed, {test161} can also be installed from sources. See the
https://github.com/ops-class/test161/blob/master/README.adoc[README] for more
details.

Once you have installed {test161} you should be able to run it and see output
like this:

[source,role='noautohighlight']
----
$ test161
usage:
    test161  <command> <flags> <args>

    test161 run [-dry-run | -d] [-explain | -x] [sequential | -s]
                [-no-dependencies | -n] [-verbose | -v (whisper|quiet|loud*)]
                [-tag] <names>

    test161 submit [-debug] [-verify] [-no-cache] <target> <commit>

    test161 list (targets|tags|tests) [-remote | -r]

    test161 config [-debug] [(add-user|del-user|change-token)] <username> <token>

    test161 version

    test161 help for a detailed commands description
----

=== {os161} Dependencies

You should be able to use {test161} to test any {os161}-based kernel--but it
is easiest to start with our {ops-os161}. Here are some of the changes that we
have made to OS/161 to support automated testing and how to apply them to your
OS/161 tree if you are not using our sources. (And if you are an instructor
using {os161}, let's collaborate on maintaining OS/161! Please contact us.)

==== Environment Inference

To run and submit your OS/161 kernel, {test161} needs to be able to find your
OS/161 sources and the root directory where your kernel is installed. If you
are using the {ops-os161} this will happen automatically using symlinks
created during kernel compilation.

Otherwise, you will need to merge our changes to `mk/os161.kernel.mk`,
specifically
https://github.com/ops-class/os161/commit/3ab7073fc255dcc17d559485ae6a54c888c72766[this
commit]. It should be straightforward to merge into {os161} sources used by
other schools.

==== {test161} Configuration Files

{test161} uses a http://yaml.org[YAML]-based configuration system. To run
tests you will need configuration files for {test161}. Again, if you are using
the {ops-os161} you will already have these configuration files in a
subdirectory of your OS/161 source tree.

If not, you can easily add the
https://github.com/ops-class/test161-conf[`test161` configuration] to your
existing OS/161 sources:

[source,bash]
----
cd <your OS/161 source directory>
git clone https://github.com/ops-class/test161-conf/ test161
rm -rf test161/.git
# Do whatever you need to do to add the files to your version control system.
# Alternatively, use a Git submodule if your repository is using Git.
----

== Running {test161} Targets

[.lead]
`test161` is a very flexible tool and can rapidly run one or many tests and
evaluate their output. In this section we show you how to obtain and run
{test161} targets.

For this example, we'll assume that you want to run all tests for ASST1 and
perform grading. To do that, you provide the `asst1` target as the argument to
`test161 run`. Once you've built and installed an OS/161 kernel, here's what
happens when we run it on the base
https://github.com/ops-class/os161[`ops-class.org` OS/161 sources]:

[source,role='noautohighlight']
----
$ test161 run asst1
[boot.t          ]      0.000000        sys161: System/161 release 2.0.8, compiled Mar  2 2016 17:16:01
[boot.t          ]      0.006289
[boot.t          ]      0.006289        OS/161 base system version 2.0.1
[boot.t          ]      0.006289        Copyright (c) 2000, 2001-2005, 2008-2011, 2013, 2014
[boot.t          ]      0.006289           President and Fellows of Harvard College.  All rights reserved.
[boot.t          ]      0.227285
[boot.t          ]      0.227285        Put-your-group-name-here's system version 0 (DUMBVM #2)
[boot.t          ]      0.267567
[boot.t          ]      0.267567        764k physical memory available
[boot.t          ]      0.287666        Device probe...
[boot.t          ]      0.297720        lamebus0 (system main bus)
[boot.t          ]      0.317862        emu0 at lamebus0
[boot.t          ]      0.327908        ltrace0 at lamebus0
[boot.t          ]      0.337925        ltimer0 at lamebus0
[boot.t          ]      0.347946        beep0 at ltimer0
[boot.t          ]      0.358038        rtclock0 at ltimer0
[boot.t          ]      0.378165        lrandom0 at lamebus0
[boot.t          ]      0.388208        random0 at lrandom0
[boot.t          ]      0.398299        lhd0 at lamebus0
[boot.t          ]      0.408364        lser0 at lamebus0
[boot.t          ]      0.418427        con0 at lser0
[boot.t          ]      0.428477
[boot.t          ]      0.428477        cpu0: MIPS/161 (System/161 2.x) features 0x0
[boot.t          ]      0.458668        2 CPUs online
[boot.t          ]      0.458668        OS/161 kernel [? for menu]: 
[boot.t          ]      0.730138
[boot.t          ]      0.740156        Shutting down.
[boot.t          ]      0.740156        The system is halted.
[boot.t          ]      0.750199        sys161: 26551578 cycles (12701612 run, 13849966 global-idle)
[boot.t          ]      0.750199        sys161:   cpu0: 4714252 kern, 0 user, 135235 idle; 7626 ll, 7626/0 sc, 21863 sync
[boot.t          ]      0.750199        sys161:   cpu1: 312156 kern, 0 user, 4537331 idle; 7 ll, 7/0 sc, 15 sync
[boot.t          ]      0.750199        sys161: 1146 irqs 0 exns 0r/0w disk 2r/597w console 0r/0w/1m emufs 0r/0w net
[boot.t          ]      0.750199        sys161: Elapsed real time: 0.166175 seconds (159.781 mhz)
[boot.t          ]      0.750199        sys161: Elapsed virtual time: 0.752267915 seconds (25 mhz)
[boot.t          ]      0.750199        shutdown: normal shutdown
[synch/rwt4.t    ]      0.000000        sys161: System/161 release 2.0.8, compiled Mar  2 2016 17:16:01
[synch/lt3.t     ]      0.000000        sys161: System/161 release 2.0.8, compiled Mar  2 2016 17:16:01
[synch/sem1.t    ]      0.000000        sys161: System/161 release 2.0.8, compiled Mar  2 2016 17:16:01
[synch/lt2.t     ]      0.000000        sys161: System/161 release 2.0.8, compiled Mar  2 2016 17:16:01
[synch/rwt3.t    ]      0.000000        sys161: System/161 release 2.0.8, compiled Mar  2 2016 17:16:01
[synch/rwt5.t    ]      0.000000        sys161: System/161 release 2.0.8, compiled Mar  2 2016 17:16:01
[synch/rwt4.t    ]      0.006289
[synch/lt3.t     ]      0.006289
[synch/lt2.t     ]      0.006289
[synch/rwt3.t    ]      0.006289
[synch/rwt5.t    ]      0.006289
[synch/rwt4.t    ]      0.006289        OS/161 base system version 2.0.1
[synch/lt3.t     ]      0.006289        OS/161 base system version 2.0.1
[synch/lt2.t     ]      0.006289        OS/161 base system version 2.0.1
[synch/rwt3.t    ]      0.006289        OS/161 base system version 2.0.1

# ... lots of output omitted ...

Test                             Result                Memory Leaks        Score
------------------------------   -------------------   ------------   ----------
boot.t                           correct                        ---          0/0
synch/sem1.t                     correct                    0 bytes          0/0
synch/lt3.t                      incorrect                      ---          0/1
synch/lt1.t                      incorrect                  0 bytes          0/8
synch/lt2.t                      incorrect                      ---          0/1
synch/cvt5.t                     skip (synch/lt1.t)             ---          0/1
synch/cvt1.t                     skip (synch/lt3.t)             ---          0/4
synch/cvt2.t                     skip (synch/lt3.t)             ---          0/3
synch/cvt3.t                     skip (synch/lt3.t)             ---          0/1
synch/cvt4.t                     skip (synch/lt3.t)             ---          0/1
synch/rwt5.t                     incorrect                      ---          0/1
synchprobs/sp2.t                 skip (synch/lt3.t)             ---         0/10
synch/rwt3.t                     incorrect                      ---          0/1
synchprobs/sp1.t                 skip (synch/lt2.t)             ---         0/10
synch/rwt4.t                     incorrect                      ---          0/1
synch/rwt1.t                     incorrect                  0 bytes          0/5
synch/rwt2.t                     skip (synch/cvt2.t)            ---          0/2

Total Correct  : 2/17
Total Incorrect: 7/17
Total Skipped  : 8/17

Total Score    : 0/50
----

As you can see, {test161} has rapidly generated a lot of useful output while
also giving our base sources the score they deserve on {asst1}: 0/50! Let's
quickly go through the two parts of the {test161} output.

=== `sys161` Output

To speed execution, {test161} runs multiple tests in parallel. As a result,
test output is interleaved at parts of the testing suite where multiple tests
are being run. At the beginning of the {asst1} test suite only the boot test
is being performed because all other tests depend on it, so the output is not
interleaved. However, at the end several tests are being run in parallel and
so the output is interleaved. Output prefixes show what test generated each
output line.  This can be difficult to interpret, so `test161 run` provides a
`-s` option which performs sequential testing.

=== Test Status

Following the test output {test161} prints a summary detailing what tests were
performed and, if appropriate, how they were scored. Scoring is optional and
only performed when using certain targets.

In the example above, the output shows that the `boot` and `sem1` tests ran
correctly but earned no points. That is because the kernel booted but this was
not worth any points for {asst1}, and working semaphores are provided as part
of the base {ops-os161}. However, if the kernel had not booted the rest of the
tests would have been skipped, and if semaphores were broken many tests would
also have been skipped. In this case, both the `boot` and semaphore tests were
run because they were specified as a _dependency_ by other tests that were
included as part of the {asst1} target. {test161} can automatically run test
dependencies when appropriate.

For the next 15 tests above {test161} reports that they either failed
(`incorrect`) or were skipped (`skip`). This is unsurprising given that the
{ops-os161} do not include working locks, condition variables, or
reader-writer locks. As you complete portions of each assignment your score
will increase.

{test161} skips tests because their dependencies are not met. For the 8 tests
that were skipped above, in each case {test161} reports one of the failed or
missing dependencies that caused it to skip the test. For example, the
condition-variable tests `cvt{1,2}` depend on working locks, and these locks
did not work. Similarly, both the stoplight and whale mating synchronization
test drivers rely on working locks.

{test161} also reports memory leaks when this is enabled by the test. In some
cases above, it was not. But it is reassuring that the semaphores provided by
the {ops-os161} don't leak memory!

=== Running Single {test161} Tests

In our example above {test161} was used to run a _target_, which configures a
set of tests to be run and maps test results to point values. If you are
curious, look at the `asst1.tt` file located in the `targets` subdirectory of
your {test161} configuration directory.

But {test161} can also be a part of your development process by running single
tests and reporting their output (without scores). Here is an example, again
with the base {ops-os161}:

[source,role='noautohighlight']
----
$ test161 run synch/sem1.t
[boot.t      ]  0.000000        sys161: System/161 release 2.0.8, compiled Mar  2 2016 17:16:01
[boot.t      ]  0.006289
[boot.t      ]  0.006289        OS/161 base system version 2.0.1
[boot.t      ]  0.006289        Copyright (c) 2000, 2001-2005, 2008-2011, 2013, 2014
[boot.t      ]  0.006289           President and Fellows of Harvard College.  All rights reserved.
[boot.t      ]  0.237759

# ... lots of output omitted ...

[synch/sem1.t]  0.000000        sys161: System/161 release 2.0.8, compiled Mar  2 2016 17:16:01
[synch/sem1.t]  0.006289
[synch/sem1.t]  0.006289        OS/161 base system version 2.0.1
[synch/sem1.t]  0.006289        Copyright (c) 2000, 2001-2005, 2008-2011, 2013, 2014
[synch/sem1.t]  0.006289           President and Fellows of Harvard College.  All rights reserved.
[synch/sem1.t]  0.237964
[synch/sem1.t]  0.237964        Put-your-group-name-here's system version 0 (DUMBVM #6)
[synch/sem1.t]  0.268137
[synch/sem1.t]  0.268137        764k physical memory available
[synch/sem1.t]  0.288267        Device probe...
[synch/sem1.t]  0.298354        lamebus0 (system main bus)

# ... lots of output omitted ...

[synch/sem1.t]  3.364153        sys161:   cpu30: 327482 kern, 0 user, 40112024 idle; 43 ll, 13/30 sc, 10 sync
[synch/sem1.t]  3.364153        sys161:   cpu31: 327115 kern, 0 user, 40112391 idle; 44 ll, 13/31 sc, 10 sync
[synch/sem1.t]  3.364153        sys161: 8409 irqs 0 exns 0r/0w disk 15r/5300w console 0r/0w/1m emufs 0r/0w net
[synch/sem1.t]  3.364153        sys161: Elapsed real time: 3.686627 seconds (33.7904 mhz)
[synch/sem1.t]  3.364153        sys161: Elapsed virtual time: 3.365535757 seconds (25 mhz)
[synch/sem1.t]  3.364153        shutdown: normal shutdown

Test                             Result       Memory Leaks
------------------------------   ----------   ------------
boot.t                           correct               ---
synch/sem1.t                     correct           0 bytes

Total Correct  : 2/2
----

In this case we ran the semaphore test `sem1`, which does work in the base
sources, and {test161} produced output reflecting that. You can instruct
{test161} to omit a test's dependencies by providing the `-n` flag to `test161
run`, in which case it would have skipped the `boot` test.

=== Running Groups of Tests

The name passed to `test161 run` identifies a test relative to the `tests`
subdirectory of the the {test161} configuration directory. (If you have
installed our
https://github.com/ops-class/test161/tree/master/bash_completion[`bash`
completion script], `test161` should tab complete many things including tests
and targets.)

In this case, `synch/sem1.t` contains:

[source,yaml]
----
---
name: "Semaphore Test"
description:
  Tests core semaphore logic through cyclic signaling.
tags: [synch, semaphores, kleaks]
depends: [boot]
sys161:
  cpus: 32
---
khu
sem1
khu
----

You'll notice that the `sem1` test also belongs to three groups: `synch`,
`semaphores`, and `kleaks`. Groups provide another useful way to run
{test161}. Here we've asked {test161} to run all of the tests that are in the
`synch` group. 

[source,role='noautohighlight']
----
$ test161 run synch
Test                             Result                Memory Leaks
------------------------------   -------------------   ------------
boot.t                           correct                        ---
synch/sem1.t                     correct                    0 bytes
synch/lt3.t                      incorrect                      ---
synch/lt1.t                      incorrect                  0 bytes
synch/lt2.t                      incorrect                      ---
synch/cvt5.t                     skip (synch/lt2.t)             ---
synch/cvt1.t                     skip (synch/lt2.t)             ---
synch/cvt4.t                     skip (synch/lt3.t)             ---
synch/cvt2.t                     skip (synch/lt2.t)             ---
synch/cvt3.t                     skip (synch/lt2.t)             ---
synch/rwt3.t                     incorrect                      ---
synch/rwt2.t                     skip (synch/cvt2.t)            ---
synch/rwt4.t                     incorrect                      ---
synch/rwt1.t                     incorrect                  0 bytes
synch/rwt5.t                     incorrect                      ---

Total Correct  : 2/15
Total Incorrect: 7/15
Total Skipped  : 6/15
----


== Submitting Using `test161`

[.lead]
Once you are happy with your score on each assignment footnote:[Or with the
deadline looming...], `test161` allows you to submit your assignments for
automated grading.

With some important exceptions (see below), remote `test161` grading is
identical to the tests that you run in your local environment. As a result,
the grade or performance marks that you achieve on the remote server should
line up closely with what you achieve locally.

This also means that it is both unnecessary and discouraged to repeatedly
submit assignments using `test161`. You will notice that the remote output
from `test161` is different than what you normally see, and that many useful
messages are disabled. This is because remote automated testing is not
intended to produce diagnostic output. Iterative `test161` testing should be
done locally. If you are missing tests required to evaluate your kernel, that
is because writing them is part of the assignment. So do that, rather than
bang on the `test161` server.

=== Preparing for Submission

++++
<div class="embed-responsive embed-responsive-16by9"
		 style="margin-top:10px; margin-bottom:10px; border:1px solid grey">
<div class="youtube-container" data-id="wzS-moehW0I"></div>
</div>
++++

To submit to https://test161.ops-class.org[`test161.ops-class.org`], you
first need to retrieve your user token and public key and configure your
repository to allow `test161` to clone it during remote testing.

Log in to https://test161.ops-class.org[`test161.ops-class.org`] and click on
the profile tab. You should see a submit token, which you will need to add to
your `.test161.conf` file in a minute.

You should also see a dialog allowing you to create a new public key. The
reason for this is that `test161` needs access to your Git repository to test
it but will _not_ test public repositories. So you need to ensure that
`test161` can clone the OS/161 repository that you are going to submit with
the public key that is shown on your profile page.

How to add this key differs depending on where you host your private OS/161
Git repository. GitHub allows you to set up
https://developer.github.com/guides/managing-deploy-keys/[read-only deploy
keys], as does http://doc.gitlab.com/ce/ssh/README.html[GitLab]. *You should
not add this key to your Git user account or give it push access to your
OS/161 or any other repository.* If you are hosting your Git repository
somewhere that does not support deployment keys, we would suggest finding an
alternative that does.

=== Configuration for Submission

To submit assignments we have to add a few new values to your `.test161.conf`
file, wherever you put it. Here's what we started with above and what was
sufficient for local testing:

[source,role='noautohighlight']
----
rootdir: /home/trinity/root/
test161dir: /home/trinity/src/test161/
----

For remote submission you to add values that tell `test161` where to submit
your assignment, how to get your code, and who you are working with. Here's
an example:

[source,role='noautohighlight']
----
rootdir: /home/trinity/root/
test161dir: /home/trinity/src/test161/
server: https://test161.ops-class.org
repository: git@gitlab.ops-class.org:staff/os161.git
users:
  - email: "challen@buffalo.edu"
    token: "MYSECRETTOKEN"
  - email: "mypartner@buffalo.edu"
    token: "HERSECRETTOKEN"
----

The `token` value is the token that is shown on your
https://test161.ops-class.org[`test161.ops-class.org`] profile page. If you
are working with a partner you should add their email address and token as
shown above. Contact them privately to get their token. If you are working
alone only submit on behalf of yourself.

At any point you can use the
https://test161.ops-class.org[`test161.ops-class.org`] web interface to
regenerate a new public key or private token. This is particularly important
if you end a partnership to ensure that your partner can no longer submit on
your behalf.

=== Submitting Your Assignment

++++
<div class="embed-responsive embed-responsive-16by9"
		 style="margin-top:10px; margin-bottom:10px; border:1px solid grey">
<div class="youtube-container" data-id="5i1_C-w46HA"></div>
</div>
++++

If you have followed the instructions above then you are ready to submit your
assignment. But before you do, *please test locally using `test161 run`*. Our
server is not intended to be part of your testing and development
process--that's why we provided a local client and grading approximations.

That said, _please submit early and often_ once you have code that you are
somewhat happy with. It is better to submit a few hours beforehand and lock
in partial credit than wait until the minutes before the deadline when you
might not receive any points.

Once you are happy with the score that you earned using `test161 run`, there
are a few other things you need to do before submitting. First, make sure
that all of your changes are checked in and that the tip of the branch that
you are working on has the changes that you want to submit. Second, make sure
that the changes are pushed to the remote repository you configured in your
`.test161.conf` file.

The best way to check for this is to run `git status`. This is bad output,
and indicates that you need to commit your changes:
[source,bash]
----
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
...
----

This is also bad output and indicates that you need to push your changes to
your remote:
[source,bash]
----
$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
----

This is what you want to see:
[source,bash]
----
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
----

The next thing to ensure is that you've earned some points on the assignment.
`test161` will not allow you to submit code that earns a zero. Use `test161
run` to determine this.

At that point you should be ready to submit. You need to run the `test161
submit <target>` command from your Git source directory. When you do, the
following steps will take place locally:

. `test161` will clone a copy of the Git repository in your `.test161.conf`
file into a temporary directory and check out the commit that you are
submitting. This can fail if you have not pushed your changes.

. `test161` will then configure and build your kernel. This can fail or
produce incorrect results if you have uncommitted changes in your working
tree.

. `test161` will then run and the kernel that it built by running `test161
run <target>`. If you have not earned any points you will not be able to
submit. If you have earned some points, `test161` will ask you to confirm
your submission and agree to the course collaboration policy before
submitting. This is mandatory.

At that point the action moves to the
https://test161.ops-class.org[`test161.ops-class.org`] server. You can watch
the live testing process if you are logged in and have all or that submission
target selected. The server-side testing process is fundamentally no
different than the local testing process, with a few caveats described below.
Hopefully, when testing completes you have earned the score that you were
expecting.

Note that testing and grading may not happen immediately. If the `test161`
server receives many requests the process will slow down and future
submissions will be delayed. *Keep this in mind when submitting close to the
deadline!* Your submission will be timestamped when the request arrives on
our server, but you may not be able to see the testing results until after
the deadline has passed.

Congrats! You submitted your assignment.

==== Troubleshooting

Here is a list of things to try if your submission is not succeeding, either
locally or remotely:

. Try updating your copy of `test161` by running `go get -u
github.com/ops-class/test161/test161`. This is always safe to do.

. Make sure that all of your changes are checked in and pushed to your
remote repository.

. If you have configured a remote in your `.test161.conf` file, make sure it
matches the one that you are pushing and pulling from.

. Make sure that the https://test161.ops-class.org[`test161.ops-class.org`]
server can use the public key that you have configured through the web
interface to pull from the repository that you are submitting.

Here is a list of things to try if you are not getting as much credit as you
deserve:

. If the assignment required you to write certain tests, make sure that they
are complete and accurate.

. Make sure that `test161 run` is testing the same kernel that you are
submitting! This can happen if the root directory configured in your
`.test161.conf` file is different from where you are installing your kernels
and, as a result, hosts a stale kernel file. Check the file timestamps after
a `bmake install`.

. Examine the server logs to determine what went wrong and use that to focus
your local testing.

=== Differences Between the Local and Remote Testing Environments

One of the design goals of `test161` is to make local evaluation as accurate
as possible. However, there are some differences between your local test
environment and the remote one.

Specifically, before performing remote testing `test161` applies an _overlay_
to your kernel which removes some files and replaces the contents of others.
For example, we overwrite all of your ``Makefiles``s and anything else that
we have to interpret or run to make sure that you don't try to damage our
server. We also overwrite all of the tests in `kern/test` with trusted code
to ensure that your kernel is running our tests and that you didn't rewire
the menu to try and trick the testing suite footnote:[We have a few other
tricks up our sleeve here, so I wouldn't bother trying to flummox the remote
grader. Doing the assignment is probably easier.].

=== Cheating Detection

Finally, note that each repository submitted to the
https://test161.ops-class.org[`test161.ops-class.org`] server will be checked
in its entirely for plagiarism: *every file, and every commit*, not limited
to submissions. Any evidence of plagiarism will be forwarded to the relevant
course staff and plagiarized assignments will be removed from the `test161`
results.

== Writing `test161` Tests

[.lead]
`test161` is designed to allow you to test your kernel using both the tests
we have provided and new tests that you may write for each assignment.

Below we describe how to create and run your own `test161` scripts. But
first, we describe the three key components of the `test161` configuration
directory: tests, commands, and targets.

=== Tests

The main `test161` configuration object is a test, which are stored in files
with a `.t` extension footnote:[In homage to the original `test161` tool that
David wrote years ago that also used a `.t` extension.]. Here is an example
from `test161/synch/sem1.t`:

[source,role='noautohighlight']
----
---
name: "Semaphore Test"
description:
  Tests core semaphore logic through cycling signaling.
tags: [synch, semaphores]
depends: [boot]
sys161:
  cpus: 32
---
sem1
----

==== Front matter

The test consist of two parts. The header in between the first and second
`---` is http://yaml.org[YAML] front matter that provides test metadata. Here
it provides the name and a description of the test, includes the test in the
`synch` and `semaphores` tags, indicates that the test depends on the `boot`
test group, and configures `sys161` to run the test with 32 cores.

We will eventually provide more detail about test configuration options on
the https://github.com/ops-class/test161[GitHub page], but for now you can
get a sense for the options by reading other test files and looking at the
https://github.com/ops-class/test161#default-settings[`test161` defaults].
About the only commonly useful option not used by `sem1.t` is a `ram` option
for `sys161`.

==== Test inputs

After the front matter comes the test itself. `test161` tests can be
considered series of inputs to the `sys161` simulator, plus a bit of
https://github.com/ops-class/test161#testfile-syntactic-sugar[syntactic
sugar]. For example, in this case note that we did not need to explicitly
shut the kernel down: `sem1` expands automatically to `sem1; q`.

This is particularly useful when running commands from the shell. `test161`
provides a `$` prefix indicating that a command should be run from the shell,
and knows how to start and exit the shell as appropriate. So this single
command:

[source,role='noautohighlight']
----
$ /bin/true
----

expands to:

[source,role='noautohighlight']
----
s
/bin/true
exit
q
----

==== Groups of tests

`test161` allows you to group tests together using tags. For example, the
`sem1.t` test above is part of both the `semaphores` group (by itself) and
the `synch` group with a bunch of other tests, including `rwt{1-4}`,
`cvt{1-5}`, etc. Tags can be used both as arguments to `test161 run`:

[source,bash]
----
test161 run synch
----

and as dependencies to other tests. As shown above, the `sem1.t` test depends
on the `boot` group which currently consists only of `test161/boot.t`. Here
is another example from `cvt1.t`:

[source,role='noautohighlight']
----
---
name: "CV Test 1"
description:
  Tests core CV functionality through cyclic waiting.
tags: [synch, cvs]
depends: [boot, semaphores, locks]
sys161:
  cpus: 32
---
cvt1
----

Note that `cvt1.t` depends on `boot`, `locks` (since CVs require working
locks), and `semaphores` (since the test uses semaphores to shut down
cleanly).

=== Identifying single tests

Single tests can also be passed to `test161 run` or used as dependencies.
Single tests are identified by the relative path to the test file from the
`test161` configuration directory. For example, to run `boot.t` you would run
`test161 run boot.t`, and to run the `sem1.t` located in
`test161/synch/sem1.t` you would run `test161 run synch/sem1.t`.

Dependencies use the same syntax, _regardless of where the file that is
expressing the dependency is located_. For example, in `synch/cvt2.1.` we
could use `depends: [boot.t]`, or `depends: [synch/lt1.t]`.

=== Commands

`test161` tests consist of a series of _commands_ that are actually executed
by the running OS/161 kernel or shell. To process the output of a test,
`test161` needs to know what it should expect each test to do and what
constitutes success and failure. For example, some of our stability tests
intentionally create a panic, and in other cases tests may intentionally
hang: like `/testbin/forkbomb` for link:/asst/2/[ASST2].

`test161` reads this information from all files with `.tc` extensions in the
`commands` subdirectory. Files in that directory are again in
http://yaml.org[YAML] syntax and can be processed in any order. Here is a
snippet from `commands/

[source,role='noautohighlight']
----
templates:
  - name: sem1
  - name: lt1
	...
  - name: lt2
    panics: yes
    output:
      - text: "lt2: Should panic..."
----

Each commands file should define a single `templates` object consisting of an
array of output templates. Each names a single command, such as `sem1`, and
describes the output. By default, for tests that are only listed in a `.tc`
file `test161` will expect that output `<command name>: SUCCESS` indicates
success and the absence of this string indicates failure. Note that commands
must be named in a command file for this default to apply. Some commands,
like `q` and `exit`, do not succeed or fail--as long as they do not panic,
which `test161` monitors separately. So they are omitted from the `.tc` file.

// TODO: Beef up once we have ASST2 stuff.

The commands file can also indicate more about the expected output. For
example, the entry above for `lt2` indicates that it should panic on success
and print `lt2: Should panic` before panicking.

=== Targets

Tests and commands allow `test161` to run test scripts to evaluate your
OS/161 kernel. However, grading assignments requires one additional
components: _targets_.

Target files have a `.tt` extension and live in the `targets` subdirectory.
Each target configures a set of tests to run and their point values as well
as the kernel configuration and overlay used to build your kernel for that
specific target. Here is an example again drawn from link:/asst/1/[ASST1]:

[source,role='noautohighlight']
----
name: asst1
version: 1
points: 50
type: asst
kconfig: ASST1
tests:
  - id: synch/lt1.t
    points: 8
  - id: synch/lt2.t
    points: 1
  - id: synch/lt3.t
    points: 1
...
----

// TODO: Beef up performance targets once we have some.

Format is again, http://yaml.org[YAML]. This target tells `test161` to use
the `ASST1` kernel configuration file, that there should be 50 total points
included in all of the tests, and that this is a assignment-type
configuration. We will also eventually distribute performance targets
allowing you to race your OS/161 kernel against other students.

// TODO: Partial credit.

After the configuration each target includes a lists of tests to run,
identified using the single-test format described above. It also maps test
success output to points, and includes flexible ways to give partial credit
for tests and commands that support partial credit.
